"""Gemini-powered radiology report refiner using the Google Files API.

This module adds Step 8 to the SAE-FRAG RAG pipeline:
  X-ray images → Gemini Files API upload → Gemini multimodal refinement

The refiner accepts all contextual signals produced by pipeline Steps 1-7
and uses Gemini to produce a clinically polished final report:
  - X-ray images (uploaded via Files API for visual grounding)
  - Verified retrieved report  (FAISS + cross-modal re-ranking)
  - Detected pathology entities (soft-AND of image + report classifiers)
  - T5 draft report (from HybridReportGenerator)

Usage
-----
    refiner = GeminiReportRefiner(api_key="...")   # or set GEMINI_API_KEY env var
    refined_report = refiner.refine(
        image_paths=["/path/to/frontal.png", "/path/to/lateral.png"],
        verified_report="Heart size is normal ...",
        entity_vector=verified_entity_vector[0],   # (14,) float tensor
        draft_report="The cardiac silhouette appears...",
        verify_score=0.87,
    )
"""

from __future__ import annotations

import logging
import os
import time
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

# 14-class CheXpert-style pathology labels matching SAEImageClassifier / ReportClassifier
PATHOLOGY_LABELS: List[str] = [
    "Atelectasis",
    "Cardiomegaly",
    "Consolidation",
    "Edema",
    "Effusion",
    "Emphysema",
    "Fibrosis",
    "Hernia",
    "Infiltration",
    "Mass",
    "Nodule",
    "Pleural Thickening",
    "Pneumonia",
    "Pneumothorax",
]

_SYSTEM_PROMPT = (
    "You are a board-certified radiologist reviewing a chest X-ray study. "
    "You have access to:\n"
    "  1. The actual chest X-ray image(s)\n"
    "  2. A clinically verified retrieved report from a similar case\n"
    "  3. Pathology findings confirmed by both the image and text classifiers\n"
    "  4. A draft report generated by an AI model\n\n"
    "Your task is to synthesise all of this information and write a final, "
    "refined radiology report with clearly separated FINDINGS and IMPRESSION "
    "sections. Be factual, concise, and clinically precise. Do NOT hallucinate "
    "findings that are not supported by the imaging evidence or the provided context."
)


class GeminiReportRefiner:
    """Refine T5-generated radiology reports using the Gemini Files API.

    Parameters
    ----------
    api_key:
        Google Gemini API key.  Falls back to the ``GEMINI_API_KEY``
        environment variable when not supplied.
    model:
        Gemini model identifier (default ``gemini-2.0-flash``).
    entity_threshold:
        Minimum soft-AND confidence to treat a pathology as *active*
        (default 0.3).
    cache_uploads:
        Re-use uploaded file URIs within the same session to avoid
        redundant uploads and API quota consumption (default ``True``).
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "gemini-2.0-flash",
        entity_threshold: float = 0.3,
        cache_uploads: bool = True,
    ) -> None:
        try:
            from google import genai as _genai
        except ImportError as exc:
            raise ImportError(
                "google-genai is required.  Install with:  pip install google-genai"
            ) from exc

        resolved_key = api_key or os.environ.get("GEMINI_API_KEY")
        if not resolved_key:
            raise ValueError(
                "A Gemini API key is required.  Pass api_key= or set "
                "the GEMINI_API_KEY environment variable."
            )

        self._genai = _genai
        self.client = _genai.Client(api_key=resolved_key)
        self.model = model
        self.entity_threshold = entity_threshold
        # maps abs_path → uploaded File object; None disables caching
        self._upload_cache: Optional[Dict[str, object]] = {} if cache_uploads else None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def refine(
        self,
        image_paths: List[str],
        verified_report: str,
        entity_vector,
        draft_report: str,
        verify_score: float = 0.0,
    ) -> str:
        """Return a Gemini-refined radiology report.

        Parameters
        ----------
        image_paths:
            Paths to the original X-ray image file(s) on disk.  Both
            frontal and lateral views are supported.
        verified_report:
            Best-matching report retrieved from FAISS and re-ranked by
            ``ReportVerifier``.
        entity_vector:
            Per-pathology soft confidence values (14-dim), produced by the
            soft-AND fusion of image and report classifiers.  Accepts a
            ``torch.Tensor`` or any iterable of floats.
        draft_report:
            The T5 ``HybridReportGenerator``'s initial generation.
        verify_score:
            Cross-modal verification score of the retrieved report
            (used for informational context in the prompt).

        Returns
        -------
        str
            Gemini-refined final report.
        """
        from google.genai import types as _types

        # --- Step 8a: upload images via Files API ---
        image_parts = self._upload_images(image_paths)

        # --- Step 8b: build structured context prompt ---
        active_entities = self._active_entities(entity_vector)
        text_prompt = self._build_prompt(
            verified_report, active_entities, draft_report, verify_score
        )

        # --- Step 8c: call Gemini ---
        parts = image_parts + [_types.Part.from_text(text=text_prompt)]
        response = self.client.models.generate_content(
            model=self.model,
            contents=parts,
            config=_types.GenerateContentConfig(
                system_instruction=_SYSTEM_PROMPT,
                temperature=0.2,       # low → factual / deterministic output
                max_output_tokens=512,
            ),
        )
        return response.text.strip()

    def cleanup_uploads(self) -> None:
        """Delete all cached Files API uploads to free quota.

        Call this at the end of an inference run if you uploaded many images.
        """
        if self._upload_cache is None:
            return
        for path, uploaded in list(self._upload_cache.items()):
            try:
                self.client.files.delete(name=uploaded.name)
                logger.debug("Deleted uploaded file: %s  (%s)", uploaded.name, path)
            except Exception as exc:
                logger.warning("Could not delete %s: %s", uploaded.name, exc)
        self._upload_cache.clear()

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _upload_images(self, image_paths: List[str]) -> list:
        """Upload each image via Files API and return a list of Part objects."""
        from google.genai import types as _types

        parts = []
        for path in image_paths:
            abs_path = str(Path(path).resolve())
            cached = (
                self._upload_cache.get(abs_path)
                if self._upload_cache is not None
                else None
            )
            if cached is None:
                cached = self._upload_with_retry(abs_path)
                if self._upload_cache is not None:
                    self._upload_cache[abs_path] = cached
                logger.debug("Uploaded %s  →  URI=%s", abs_path, cached.uri)

            parts.append(
                _types.Part.from_uri(
                    file_uri=cached.uri,
                    mime_type=cached.mime_type or _infer_mime(abs_path),
                )
            )
        return parts

    def _upload_with_retry(self, path: str, retries: int = 3):
        """Upload *path* to the Files API with exponential-backoff retry."""
        mime = _infer_mime(path)
        for attempt in range(retries):
            try:
                return self.client.files.upload(
                    file=path,
                    config=self._genai.types.UploadFileConfig(mime_type=mime),
                )
            except Exception as exc:
                if attempt == retries - 1:
                    raise
                wait = 2 ** attempt
                logger.warning(
                    "Files API upload failed (attempt %d/%d): %s — retrying in %ds",
                    attempt + 1, retries, exc, wait,
                )
                time.sleep(wait)

    def _active_entities(self, entity_vector) -> List[str]:
        """Return the label names whose soft-AND score meets the threshold."""
        try:
            scores = (
                entity_vector.cpu().tolist()
                if hasattr(entity_vector, "cpu")
                else list(entity_vector)
            )
        except Exception:
            scores = list(entity_vector)

        return [
            label
            for label, score in zip(PATHOLOGY_LABELS, scores)
            if score >= self.entity_threshold
        ]

    @staticmethod
    def _build_prompt(
        verified_report: str,
        active_entities: List[str],
        draft_report: str,
        verify_score: float,
    ) -> str:
        entities_str = (
            ", ".join(active_entities) if active_entities else "None detected"
        )
        return (
            f"--- VERIFIED RETRIEVED REPORT  (cross-modal score: {verify_score:.4f}) ---\n"
            f"{verified_report.strip()}\n\n"
            f"--- DETECTED PATHOLOGY FINDINGS (soft-AND: image × text classifiers) ---\n"
            f"{entities_str}\n\n"
            f"--- AI DRAFT REPORT  (Flan-T5 HybridReportGenerator) ---\n"
            f"{draft_report.strip()}\n\n"
            "--- YOUR TASK ---\n"
            "Using the chest X-ray image(s) above together with all the context "
            "provided, write a refined, clinically accurate final report.  "
            "Structure the output with clearly labelled FINDINGS and IMPRESSION "
            "sections."
        )


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def _infer_mime(path: str) -> str:
    """Return the MIME type for common imaging extensions."""
    ext = Path(path).suffix.lower().lstrip(".")
    return {
        "jpg": "image/jpeg",
        "jpeg": "image/jpeg",
        "png": "image/png",
        "tiff": "image/tiff",
        "tif": "image/tiff",
    }.get(ext, "image/jpeg")
